name: 'Create elasticbeanstalk deployment'
description: 'Create elasticbeanstalk deployment'
inputs:
  environment:
    description: 'Environment name'
    required: true
  github-token:
    description: 'Github token'
    required: true
  target:
    description: 'Deployment target'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Download deploy file
      uses: actions/download-artifact@v4
      with:
        name: deploy-file-${{ inputs.environment }}
    - name: Create package file with ssm configuration
      shell: bash
      run: |
        mkdir -p .ebextensions
        cat <<-EOF > .ebextensions/ssm.config
        option_settings:
          aws:elasticbeanstalk:application:environment:
            DBURL: '{{resolve:ssm:/${{ inputs.target }}/DBURL:1}}'
            DBUSER: '{{resolve:ssm:/${{ inputs.target }}/DBUSER:1}}'
            DBPASS: '{{resolve:ssm:/${{ inputs.target }}/DBPASS:1}}'
            _AWS_KEY: '{{resolve:ssm:/${{ inputs.target }}/_AWS_KEY:1}}'
            _AWS_SECRET: '{{resolve:ssm:/${{ inputs.target }}/_AWS_SECRET:1}}'
        EOF
        jar uf BTC-1.0.0.war .ebextensions/ssm.config
    - name: Archive WAR file
      uses: actions/upload-artifact@v4
      with:
        name: deploy-file-${{ inputs.target }}
        path: target/*.war
