name: 'Create elasticbeanstalk deployment'
description: 'Create elasticbeanstalk deployment'
inputs:
  environment:
    description: 'Environment name'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create ssm configuration
      shell: bash
      run: |
        cat <<-EOF > src/main/.ebextensions/ssm.config
        option_settings:
          aws:elasticbeanstalk:application:environment:
            DBURL: '{{resolve:ssm:/${{ inputs.environment }}/DBURL:1}}'
            DBUSER: '{{resolve:ssm:/${{ inputs.environment }}/DBUSER:1}}'
            DBPASS: '{{resolve:ssm:/${{ inputs.environment }}/DBPASS:1}}'
        EOF
    - name: Maven and deployment packaging
      shell: bash
      run: |
        [ ! -f src/main/.ebextensions/ssm.config ] && echo "SSM configuration not created" && exit 1
        mvn clean package
#    - name: Archive deploy file
#      uses: actions/upload-artifact@v4
#      with:
#        name: deploy-file-${{ inputs.environment }}
#        path: deploy.zip
    - name: Archive WAR file
      uses: actions/upload-artifact@v4
      with:
        name: deploy-file-${{ inputs.environment }}
        path: target/*.war
