name: 'Create elasticbeanstalk deployment'
description: 'Create elasticbeanstalk deployment'
inputs:
  environment:
    description: 'Environment name'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
  aws-secret-access-key:
    description: 'AWS secret access key'
  aws-region:
    description: 'AWS region'
    default: ap-southeast-2
runs:
  using: "composite"
  steps:
    - name: Download deploy file
      uses: actions/download-artifact@v4
      with:
        name: deploy-file-${{ inputs.environment }}
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ inputs.aws-access-key-id }}
        aws_secret_key: ${{ inputs.aws-secret-access-key }}
        application_name: java-demo
        environment_name: java-demo-env
        version_label: ${{ inputs.environment }}.${{ github.sha }}
        region: ${{ inputs.aws-region }}
        deployment_package: demo-java-app.war

