name: Deploy application to Staging

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/ebs-prod-deployment.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-war-file
        with:
          environment: staging
          github-token: ${{ secrets.GH_TOKEN }}

  config:
    strategy:
      matrix:
        target: [
          BTC-100-TEST
        ]
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/create-eb-deployment
        with:
          environment: staging
          target: ${{ matrix.target }}
          github-token: ${{ secrets.GH_TOKEN }}

  deploy:
    environment: STAGING
    strategy:
      matrix:
        target: [
          BTC-100-TEST
        ]
    runs-on: ubuntu-latest
    needs: [ config, build ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/push-deployment-to-eb
        with:
          target: ${{ matrix.target }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          application-name-prefix: ${{ matrix.environment }}
          environment-name-prefix: ${{ matrix.environment }}
          package-filename: BTC-1.0.0-${{ matrix.environment }}.war
          wait-for-eb-deployment: false