name: Deploy application to Staging

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        environment: [ staging ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/create-eb-deployment
        with:
          environment: ${{ matrix.environment }}

  deploy:
    environment: STAGING
    strategy:
      matrix:
        environment: [ staging ]
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/push-deployment-to-eb
        with:
          environment: ${{ matrix.environment }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2